spring:
  application:
    name: crud_demo
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update

  logging:
    level:
      # Set the default logging level for your specific package to DEBUG
      com.practice.crud_demo: DEBUG
